### ISSUE TITLE
Error when deployed to heroku which prevents the bot being online

### ISSUE THREAD

**Issue by ShekharReddy4** [ShekharReddy4/iambot#1]
When I try to deploy the bot to Heroku I get an error something like this : https://gist.github.com/ShekharReddy4/9967c0d775608f1a7049a7d3378a7cf8

**Comment by dosten** [comment]
You need `libicu` installed in your system, AFAIK you can't do this in Heroku.

**Comment by ShekharReddy4** [comment]
Closing this for now :)
